export default {
    ACTION_JOIN_ROOM: 'JOIN_ROOM',
    ACTION_JOIN_ROOM_BY_NAME_AND_PASSWORD: 'ACTION_JOIN_ROOM_BY_NAME_AND_PASSWORD',
    ACTION_CREATE_NEW_ROOM: 'ACTION_CREATE_NEW_ROOM',
    ACTION_SET_ADMIN: 'ACTION_SET_ADMIN',
    ACTION_JOIN_ROOM_BY_ID: 'ACTION_JOIN_ROOM_BY_ID',
    ACTION_REQUEST_ROOM_DETAILS: 'ACTION_REQUEST_ROOM_DETAILS',
    ACTION_LEAVE_ROOM: 'ACTION_LEAVE_ROOM',

    // user roles
    USER_ROLE_ADMIN: 'USER_ROLE_ADMIN',
    USER_ROLE_VOTER: 'USER_ROLE_VOTER',
    USER_ROLE_PREVIEW: 'USER_ROLE_PREVIEW',

    EVENT_ROOM_NOT_FOUND: 'EVENT_ROOM_NOT_FOUND',
    EVENT_CREATE_ROOM: 'EVENT_CREATE_ROOM',
    EVENT_JOINED_ROOM: 'EVENT_JOINED_ROOM',
    EVENT_ROOM_DETAILS_UPDATE: 'EVENT_ROOM_DETAILS_UPDATE',
    EVENT_CHANGE_LAST_VISITED_ROOM_DETAILS: 'EVENT_CHANGE_LAST_VISITED_ROOM_DETAILS',


    // ----
    // USER
    // ----


    ACTION_REGISTER_NEW_USER: 'ACTION_REGISTER_NEW_USER',
    ACTION_REGISTER_USER_BY_ID: 'ACTION_REGISTER_USER_BY_ID',
    ACTION_REGISTER_USER_BY_NAME_AND_PASSWORD: 'ACTION_REGISTER_USER_BY_NAME_AND_PASSWORD',
    ACTION_CLEAR_USER_DETAILS: 'ACTION_CLEAR_USER_DETAILS',

    ACTION_FORGET_ABOUT_LAST_VISITED_ROOM: 'ACTION_FORGET_ABOUT_LAST_VISITED_ROOM',
    ACTION_REQUEST_USER_DETAILS: 'ACTION_REQUEST_USER_DETAILS',

    EVENT_USER_NOT_FOUND: 'EVENT_USER_NOT_FOUND',
    EVENT_CHANGE_SAVED: 'EVENT_CHANGE_SAVED',
    EVENT_USER_REGISTERED: 'EVENT_USER_REGISTERED',
    EVENT_USER_CHANGED_REGISTER_STATUS: 'EVENT_USER_CHANGED_REGISTER_STATUS',
    EVENT_USER_REGISTER_FAIL: 'EVENT_USER_REGISTER_FAIL',
    EVENT_USER_DETAILS: 'EVENT_USER_DETAILS',
    EVENT_REGISTER_USER_ALREADY_EXISTS: 'EVENT_REGISTER_USER_ALREADY_EXISTS'
};
