export default {
    ACTION_START_NEW_VOTING: 'ACTION_START_NEW_VOTING',
    ACTION_FINISH_VOTING: 'ACTION_FINISH_VOTING',
    ACTION_CONTINUE_VOTING: 'ACTION_CONTINUE_VOTING',
    ACTION_STOP_VOTING: 'ACTION_STOP_VOTING',
    ACTION_VOTE: 'ACTION_VOTE',

    STATUS_PENDING: 'STATUS_PENDING',
    STATUS_IN_PROCESS: 'STATUS_IN_PROCESS',
    STATUS_FINISHED: 'STATUS_FINISHED',

    EVENT_VOTING_STATUS_CHANGED: 'EVENT_VOTING_STATUS_CHANGED',
    EVENT_USERS_ALREADY_VOTED: 'EVENT_USERS_ALREADY_VOTED',
    EVENT_USERS_VOTES: 'EVENT_USERS_VOTES',
    EVENT_USER_VOTE: 'EVENT_USER_VOTE'
};